title: 'blackandpink'
description: "A minimal Jekyll theme"
baseurl: "/"

header_pages:
    - index.md
    - about.md

style: dark

footer: 'follow me on <a href="https://twitter.com/">twitter</a>'

markdown: kramdown
theme: blackandpink
highlighter: rouge

# google_analytics: xxx
# disqus:
#     shortname: xxx
